name: warpforge

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:

env:
  GO_VERSION: '1.18'

jobs:
  serum:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Clone Serum Analyzer
      uses: actions/checkout@v3
      with:
        repository: serum-errors/go-serum-analyzer
        ref: master
        path: go-serum-analyzer
    - name: Install Serum Analyzer
      working-directory: go-serum-analyzer
      run: go install ./cmd/go-serum-analyzer/
    - name: Run Serum Analyzer
      run: go-serum-analyzer ./...
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Clone warplark
      uses: actions/checkout@v3
      with:
        repository: warptools/warplark
        ref: main
        path: warplark
    - name: Install warplark
      working-directory: warplark
      run: go install ./...
    - name: Run Tests
      run: go test ./...
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - run: mkdir /tmp/bundle
    - run: cp plugins/* /tmp/bundle
    - name: Build warpforge binary
      run: go build -o /tmp/bundle/warpforge cmd/warpforge/*.go
    - name: Create release tarball
      run: tar -C /tmp/bundle/ -czvf warpforge.tgz .
    - name: Archive release tarball
      uses: actions/upload-artifact@v3
      with:
        name: warpforge.tgz
        path: warpforge.tgz
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@v0.6.0
      - run: go vet -vettool=$(which nilness) ./...
